# Site settings
title: "JoÃ£o Costa - CV"
description: "Site Reliability Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "JoÃ£o Costa"
resume_title:                   "Site Reliability Engineer"
resume_locations:               "Lisbon, PT ğŸ‡µğŸ‡¹ - Past: London, UK ğŸ‡¬ğŸ‡§ Toronto, CA ğŸ‡¨ğŸ‡¦ï¸ , Antibes, FR ğŸ‡«ğŸ‡·ï¸"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "joaopccosta@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-"
resume_contact_address:         "-"

resume_header_contact_info:     "joaopccosta@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>My name sounds like light sabers or racing cars. I like to make, break, and automate infrastructure and software for a living. Proud father, 2nd Dan JKA Shotokan karate (æŠ¼å¿!), and heavy metal guitarist.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/joaopccosta"
  resume_twitter_url:           "http://twitter.com/joaopccosta"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_soundcloud_url:        "https://soundcloud.com/joaopccosta"
#   resume_facebook_url:          "https://soundcloud.com/joaopccosta"
  resume_linkedin_url:          "https://www.linkedin.com/in/joaopccosta"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
#   resume_certifications_url:     "https://www.youracclaim.com/badges/1342bcde-4e06-487d-a2f1-57cee640ee4e/linked_in"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
